name: 01 - Building Blocks
on:
  - workflow_dispatch
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello, World!"
  goodbye-world:
    runs-on: ubuntu-latest
    steps:
      - name: Fixed Step
        run: |
          echo "This Step is based on a Multine Command"
          echo "This Step have been fixed and now it will not fail"
          exit 0
      - name: Say Goodbye World
        run: echo "Goodbye, World!"