name: 03 - Worflow Runners
on: push
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo on Ubuntu
        run: echo "This is running on Ubuntu"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Echo on Windows
        run: echo "This is running on Windows"
  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Echo on macOS
        run: echo "This is running on macOS"