name: 04 - Using Actions
on:
  - push
  - workflow_dispatch
jobs:
  react-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Printing Folders
        run: ls -la
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install Dependencies
        working-directory: ./04-using-actions
        run: npm ci
      - name: Run Tests
        working-directory: ./04-using-actions
        run: npm run test