name: 05 - 02 - Events Filters and Activity Types
on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches: main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event
        run: echo "Running whenever a pull request is closed on the main branch"
