name: 06 - Contexts
on:
  - push
  - workflow_dispatch
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Echo GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
      - name: Echo Runner Context
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Temp Directory: ${{ runner.temp }}"
      - name: Echo Job Context
        run: |
          echo "Job Status: ${{ job.status }}"
          echo "Job Conclusion: ${{ job.status || 'N/A' }}"
      - name: Echo Workflow Context
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Number: ${{ github.run_number }}"