name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Simulate build status (success or fail)'
        type: choice
        required: true
        options:
          - 'success'
          - 'fail'
        default: 'success'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
    steps:
      - name: Print GITHUB_OUTPUT Path
        run: echo "GITHUB_OUTPUT is located at $GITHUB_OUTPUT"
      - name: Simulate Build Process
        id: build
        run: |
          if [ "${{ inputs['build-status'] }}" == "success" ]; then
            echo "build-status=success" >> $GITHUB_OUTPUT
          else
            echo "build-status=failure" >> $GITHUB_OUTPUT
          fi
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Check Build Status
        run: echo "Build status is ${{ needs.build.outputs.build-status }}. Proceeding with deployment."