name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Simulate build status (success or fail)'
        type: choice
        required: true
        options:
          - 'success'
          - 'fail'
        default: 'success'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      first-output: ${{ steps.build.outputs.first-output }}
      second-output: ${{ steps.build.outputs.second-output }}
    steps:
      - name: Print GITHUB_OUTPUT Path
        run: echo "GITHUB_OUTPUT is located at $GITHUB_OUTPUT"
      - name: Simulate Build Process
        id: build
        run: |
          echo "build-status=${{ inputs.build-status }} >> $GITHUB_OUTPUT"
          echo "first-output=first-value" >> $GITHUB_OUTPUT
          echo "second-output=second-value" >> $GITHUB_OUTPUT
          echo "Outputs" && cat $GITHUB_OUTPUT
          echo "mistake=true" > $GITHUB_OUTPUT
          echo "Outputs" && cat $GITHUB_OUTPUT
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Print Outputs
        run: |
          echo "Outputs" && cat $GITHUB_OUTPUT
          echo "Build Status: ${{ needs.build.outputs.build-status }}"
          echo "First Output: ${{ needs.build.outputs.first-output }}"
          echo "Second Output: ${{ needs.build.outputs.second-output }}"
      - name: Check Build Status
        run: echo "Build status is ${{ needs.build.outputs.build-status }}. Proceeding with deployment."
