name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Simulate build status (success or fail)'
        type: choice
        required: true
        options:
          - 'success'
          - 'fail'
        default: 'success'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
    steps:
      - name: Print GITHUB_OUTPUT Path
        run: echo "GITHUB_OUTPUT is located at $GITHUB_OUTPUT"
      - name: Simulate Build Process
        id: build
        run: |
          echo "build-status=${{ inputs['build-status'] }} >> $GITHUB_OUTPUT"
          echo "first-output=first-value" >> $GITHUB_OUTPUT
          echo "second-output=second-value" >> $GITHUB_OUTPUT
          cat "Outputs: $GITHUB_OUTPUT"
          echo "mistake=true" > $GITHUB_OUTPUT
          cat "Outputs: $GITHUB_OUTPUT"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Print Outputs
        run: 'cat "Outputs: $GITHUB_OUTPUT"'
      - name: Check Build Status
        run: echo "Build status is ${{ needs.build.outputs.build-status }}. Proceeding with deployment."