name: 13 - Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Use cache for dependencies'
        type: boolean
        required: false
        default: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install Dependencies
        working-directory: ./13-caching
        run: npm ci
      - name: Run Tests
        working-directory: ./13-caching
        run: npm run test
      - name: Build Project
        working-directory: ./13-caching
        run: npm run build
      - name: Deploy to Staging
        run: echo "Deploying to staging environment"