name: 13 - Caching
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'NodeJs version to use'
        type: choice
        required: true
        options:
          - '20.x'
          - '22.x'
          - '24.x'
        default: '24.x'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    name: Install Dependencies
    defaults:
      run:
        working-directory: ./13-caching
    outputs:
      cache-key: ${{ steps.calculate-cache-key.outputs.cache-key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate Cache Key
        id: calculate-cache-key
        run: echo "cache-key=${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('13-caching/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 13-caching/node_modules
          key: ${{ steps.calculate-cache-key.outputs.cache-key }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm ci
  linting:
    runs-on: ubuntu-latest
    name: Linting
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./13-caching
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 13-caching/node_modules
          key: ${{ needs.install-dependencies.outputs.cache-key }}
      - name: Run Tests
        run: npm run test
      - name: Lint Code
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./13-caching
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 13-caching/node_modules
          key: ${{ needs.install-dependencies.outputs.cache-key }}
      - name: Run Tests
        run: npm run test
      - name: Build Project
        run: npm run build
      - name: Deploy to Staging
        run: echo "Deploying to staging environment"