name: 14 - Artifacts
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'NodeJs Version'
        type: choice
        required: true
        options:
          - '20.x'
          - '22.x'
          - '24.x'
        default: '24.x'
jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./14-artifacts
    outputs:
      cache-key: ${{ steps.calculate-cache-key.outputs.cache-key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate Cache Key
        id: calculate-cache-key
        run: echo "cache-key=${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('14-artifacts/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 14-artifacts/node_modules
          key: ${{ steps.calculate-cache-key.outputs.cache-key }}
      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Build Project
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: 14-artifacts-react-app
          path: 14-artifacts/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v6
        with:
          name: 14-artifacts-react-app
      - name: Deploy Application
        run: |
          echo "Deploying on Staging Environment"
          ls -R ./14-artifacts-react-app