name: 15 - Matrices Workflow
on:
  workflow_dispatch:
    inputs:
      fail-fast:
        description: 'Fail Fast'
        type: boolean
        required: true
        default: true
      ignore-expiremental:
        description: 'Ignore Experimental Versions'
        type: boolean
        required: true
        default: true
jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            node-version: 16.x
    steps:
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if Experimental Version
        if: ${{ !inputs.ignore-expiremental && matrix.node-version == '24.x' }}
        run: |
          echo "NodeJs ${{ matrix.node-version }} is experimental and not supported."
          exit 1
      - name: Run Tests
        run: sleep 5 && echo "Running tests on NodeJs ${{ matrix.node-version }} and ${{ matrix.os }} as OS"
      - name: Upload Test Results
        run: echo "Uploading test results for NodeJs ${{ matrix.node-version }} and ${{ matrix.os }}"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green, blue]
        shape: [circle, square, triangle]
        size: [small, medium, large]
        include:
          - color: red
            shape: circle
            size: small
          - color: blue
            shape: square
            size: large
    steps:
      - name: Run Example
        run: |
          echo "Running example with color: ${{ matrix.color }}, shape: ${{ matrix.shape }}, size: ${{ matrix.size }}"