name: 15 - Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Set Up NodeJs
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if Experimental Version
        if: matrix.node-version == '24.x'
        run: |
          echo "NodeJs ${{ matrix['node-version'] }} is experimental and not supported."
          exit 1
      - name: Run Tests
        run: sleep 10 && echo "Running tests on NodeJs ${{ matrix.node-version }} and ${{ matrix.os }} as OS"
      - name: Upload Test Results
        run: echo "Uploading test results for NodeJs ${{ matrix.node-version }} and ${{ matrix.os }}"
  