name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to ping.'
        type: choice
        required: true
        options:
          - https://www.google.com
          - https://invalid-url.test
          - invalid-url-format
        default: https://www.google.com
jobs:
  ping:
    name: Ping URL using Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
