name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to ping.'
        type: choice
        required: true
        options:
          - https://www.google.com
          - https://invalid-url.test
          - invalid-url-format
        default: https://www.google.com
jobs:
  ping:
    name: Ping URL using Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
      - name: Show Result
        run: |
          if [ "${{ steps.ping-url.outputs.success }}" = "true" ]; then
            echo "The URL was successfully pinged."
          else
            echo "Failed to ping the URL within the maximum free trials."
          fi
